"""Adım 7: EPW oluşturma sayfası."""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QUrl
from PySide6.QtGui import QDesktopServices
from PySide6.QtWidgets import QFileDialog, QHBoxLayout, QLabel, QLineEdit, QMessageBox, QPushButton, QVBoxLayout, QWidget

from app.core.epw_writer import export_processed_csv, write_epw_file
from app.core.validator import has_blocking_errors


class EpwExportPage(QWidget):
    def __init__(self, main_window):
        super().__init__()
        self.main_window = main_window

        layout = QVBoxLayout(self)

        row1 = QHBoxLayout()
        row1.addWidget(QLabel("Çıktı klasörü"))
        self.dir_edit = QLineEdit()
        btn_dir = QPushButton("Seç…")
        btn_dir.clicked.connect(self._pick_dir)
        row1.addWidget(self.dir_edit, 1)
        row1.addWidget(btn_dir)
        layout.addLayout(row1)

        row2 = QHBoxLayout()
        row2.addWidget(QLabel("EPW dosya adı"))
        self.name_edit = QLineEdit()
        row2.addWidget(self.name_edit, 1)
        layout.addLayout(row2)

        row3 = QHBoxLayout()
        self.btn_make = QPushButton("EPW oluştur")
        self.btn_make.clicked.connect(self._write_epw)
        self.btn_show = QPushButton("Klasörde göster")
        self.btn_show.clicked.connect(self._show_folder)
        row3.addWidget(self.btn_make)
        row3.addWidget(self.btn_show)
        layout.addLayout(row3)

        self.info = QLabel("")
        self.info.setWordWrap(True)
        layout.addWidget(self.info)
        layout.addStretch(1)

    def suggest_base_name(self) -> str:
        st = self.main_window.state
        s = st.station
        city = str(s.get("city", "city")).strip().replace(" ", "_").lower() or "city"
        code = str(s.get("wmo", s.get("station_name", "station"))).strip().replace(" ", "_").lower() or "station"
        period = str(s.get("data_period") or s.get("data_year") or "year")
        return f"{city}_{code}_{period}"

    def refresh_view(self) -> None:
        st = self.main_window.state
        if not self.dir_edit.text().strip():
            self.dir_edit.setText(st.output_folder)
        if not self.name_edit.text().strip():
            self.name_edit.setText(self.suggest_base_name() + ".epw")
        self.info.setText(f"Son EPW: {st.epw_output_path}" if st.epw_output_path else "")

    def _pick_dir(self) -> None:
        d = QFileDialog.getExistingDirectory(self, "Çıktı klasörü")
        if d:
            self.dir_edit.setText(d)
            self.main_window.state.output_folder = d

    def _parse_float(self, txt: object, field: str) -> float:
        try:
            return float(str(txt).replace(",", "."))
        except Exception as exc:
            raise ValueError(f"{field} sayısal değil.") from exc

    def _write_epw(self) -> None:
        mw = self.main_window
        st = mw.state
        mw.save_all_pages()
        try:
            mw.rebuild_processed_and_validate()
        except Exception as e:
            QMessageBox.critical(self, "Hata", str(e))
            return

        if has_blocking_errors(st.validation_results):
            QMessageBox.critical(self, "Engellendi", "Kritik veri hataları nedeniyle çıktı üretimi durduruldu.")
            return
        if st.processed_df is None:
            QMessageBox.warning(self, "Veri", "İşlenmiş veri yok.")
            return

        folder = self.dir_edit.text().strip() or st.output_folder
        if not folder:
            QMessageBox.warning(self, "Klasör", "Çıktı klasörü seçin.")
            return
        if not st.output_options.get("epw", True):
            QMessageBox.information(self, "Bilgi", "Çıktı Seçimi adımında EPW seçimi kapalı.")
            return

        file_name = self.name_edit.text().strip() or (self.suggest_base_name() + ".epw")
        if not file_name.lower().endswith(".epw"):
            file_name += ".epw"
        out_path = Path(folder) / file_name

        s = st.station
        try:
            lat = self._parse_float(s.get("latitude"), "Enlem")
            lon = self._parse_float(s.get("longitude"), "Boylam")
            tz = self._parse_float(s.get("timezone"), "Saat dilimi")
            elev = self._parse_float(s.get("elevation"), "Rakım")
            epw = write_epw_file(
                st.processed_df,
                out_path,
                city=str(s.get("city", "")),
                state_region="SS",
                country=str(s.get("country", "")),
                source=str(s.get("source") or "Custom"),
                wmo_or_code=str(s.get("wmo", "")),
                latitude=lat,
                longitude=lon,
                timezone_offset=tz,
                elevation_m=elev,
                comments1=str(s.get("description") or "Generated by Station2EPW Desktop"),
                comments2=f"Source file: {Path(st.file_path or '').name}",
            )
        except Exception as e:
            QMessageBox.critical(self, "EPW Hatası", str(e))
            return

        st.epw_output_path = str(epw)
        st.output_paths["epw"] = str(epw)

        if st.output_options.get("processed_csv"):
            p = export_processed_csv(st.processed_df, Path(folder) / f"{self.suggest_base_name()}_processed.csv")
            st.output_paths["processed_csv"] = str(p)

        if st.output_options.get("quality_report"):
            mw.refresh_report()
            rpt = Path(folder) / f"{self.suggest_base_name()}_report.txt"
            rpt.write_text(st.report_text, encoding="utf-8")
            st.output_paths["quality_report"] = str(rpt)

        self.info.setText(f"EPW oluşturuldu: {epw}")
        mw.refresh_report()
        QMessageBox.information(self, "Tamam", f"EPW oluşturuldu:\n{epw}")

    def _show_folder(self) -> None:
        p = self.main_window.state.epw_output_path
        if not p:
            return
        QDesktopServices.openUrl(QUrl.fromLocalFile(str(Path(p).parent)))
