"""PVsyst uyumlu dışa aktarımlar: CSV, SIT, MEF, paket."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd

from .epw_writer import export_processed_csv
from .project_manifest import write_project_manifest


def write_pvsyst_csv(processed_df: pd.DataFrame, station_info: dict[str, Any], output_path: str | Path, irradiance_unit: str = "W/m2") -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    df = processed_df.copy()
    dt = _build_datetime(df)

    out = pd.DataFrame(
        {
            "Date": dt.dt.strftime("%Y-%m-%d"),
            "Time": dt.dt.strftime("%H:%M"),
            "Global Horizontal Irradiance": pd.to_numeric(df.get("global_horizontal_radiation"), errors="coerce"),
            "Diffuse Horizontal Irradiance": pd.to_numeric(df.get("diffuse_horizontal_radiation"), errors="coerce"),
            "Direct Normal Irradiance": pd.to_numeric(df.get("direct_normal_radiation"), errors="coerce"),
            "Ambient Temperature": pd.to_numeric(df.get("dry_bulb"), errors="coerce"),
            "Wind Speed": pd.to_numeric(df.get("wind_speed"), errors="coerce"),
            "Relative Humidity": pd.to_numeric(df.get("relative_humidity"), errors="coerce"),
            "Precipitation": pd.to_numeric(df.get("liquid_precipitation_depth"), errors="coerce"),
            "Albedo": pd.to_numeric(df.get("albedo"), errors="coerce"),
        }
    )

    unit_txt = irradiance_unit
    # processed_df radyasyon değerleri sayısal olarak saatlik Wh/m² kabul edilir; W/m² istenirse saatlik ortalama denkliği not edilir

    header = [
        "# Station2EPW Desktop - PVsyst Export",
        f"# Station: {station_info.get('station_name', '')}",
        f"# City: {station_info.get('city', '')}",
        f"# Country: {station_info.get('country', '')}",
        f"# Latitude: {station_info.get('latitude', '')}",
        f"# Longitude: {station_info.get('longitude', '')}",
        f"# Altitude: {station_info.get('elevation', '')}",
        f"# Time Zone: {station_info.get('timezone', '')}",
        f"# Source: {station_info.get('source', '')}",
        f"# Generated at: {datetime.now().isoformat(timespec='seconds')}",
        f"# Units: Irradiance={unit_txt}, Temperature=C, WindSpeed=m/s, RH=%, Precipitation=mm, Albedo=0-1",
    ]

    csv_body = out.to_csv(index=False)
    path.write_text("\n".join(header) + "\n" + csv_body, encoding="utf-8")
    return path


def write_sit_template(station_info: dict[str, Any], output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(
        [
            "# PVsyst SIT template generated by Station2EPW",
            f"Site name={station_info.get('station_name', '')}",
            f"Country={station_info.get('country', '')}",
            f"Latitude={station_info.get('latitude', '')}",
            f"Longitude={station_info.get('longitude', '')}",
            f"Altitude={station_info.get('elevation', '')}",
            f"TimeZone={station_info.get('timezone', '')}",
            f"Source={station_info.get('source', '')}",
            "",
            "# Verify and adjust fields in PVsyst before simulation.",
        ]
    )
    path.write_text(text, encoding="utf-8")
    return path


def write_mef_template(output_path: str | Path, csv_columns: list[str]) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# PVsyst MEF import template generated by Station2EPW",
        "# This template should be reviewed according to your PVsyst version.",
        "[File]",
        "Separator=,",
        "DateFormat=YYYY-MM-DD",
        "TimeFormat=HH:MM",
        "[Columns]",
    ]
    for idx, col in enumerate(csv_columns, start=1):
        lines.append(f"{idx}={col}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def create_pvsyst_export_package(
    processed_df: pd.DataFrame,
    station_info: dict[str, Any],
    output_folder: str | Path,
    *,
    base_name: str,
    irradiance_unit: str = "W/m2",
    source_input_file: str = "",
    include_pvsyst_csv: bool = True,
    include_sit: bool = True,
    include_mef: bool = True,
    include_processed_csv: bool = True,
    include_report_txt: bool = True,
    include_manifest: bool = True,
) -> dict[str, str]:
    folder = Path(output_folder)
    folder.mkdir(parents=True, exist_ok=True)

    csv_path = None
    sit_path = None
    mef_path = None
    report_path = None
    if include_pvsyst_csv:
        csv_path = write_pvsyst_csv(processed_df, station_info, folder / f"{base_name}_pvsyst.csv", irradiance_unit=irradiance_unit)
    if include_sit:
        sit_path = write_sit_template(station_info, folder / f"{base_name}_pvsyst.SIT")
    if include_mef:
        mef_path = write_mef_template(
            folder / f"{base_name}_pvsyst.MEF",
            [
                "Date",
                "Time",
                "Global Horizontal Irradiance",
                "Diffuse Horizontal Irradiance",
                "Direct Normal Irradiance",
                "Ambient Temperature",
                "Wind Speed",
                "Relative Humidity",
                "Precipitation",
                "Albedo",
            ],
        )

    processed_path = None
    if include_processed_csv:
        processed_path = export_processed_csv(processed_df, folder / f"{base_name}_processed.csv")

    if include_report_txt:
        report_path = folder / f"{base_name}_pvsyst_report.txt"
        report_path.write_text(
            "\n".join(
                [
                    "Station2EPW PVsyst export package",
                    f"Generated: {datetime.now().isoformat(timespec='seconds')}",
                    f"Station: {station_info.get('station_name', '')}",
                    f"Irradiance unit: {irradiance_unit}",
                    "For hourly averaged irradiance data, Wh/m² over one hour is numerically equivalent to W/m² average power for that hour.",
                    "MEF template may require manual adjustment depending on PVsyst version.",
                ]
            )
            + "\n",
            encoding="utf-8",
        )

    outputs = {
        "pvsyst_csv": csv_path.name if csv_path else "",
        "sit": sit_path.name if sit_path else "",
        "mef": mef_path.name if mef_path else "",
        "processed_csv": processed_path.name if processed_path else "",
        "report": report_path.name if report_path else "",
    }

    if include_manifest:
        manifest = write_project_manifest(
            output_path=folder / f"{base_name}.pvsyst",
            station_info=station_info,
            input_file=source_input_file,
            outputs=outputs,
            source_name=station_info.get("source", "Custom Station Data") or "Custom Station Data",
        )
        outputs["manifest"] = manifest.name
    else:
        outputs["manifest"] = ""

    return {k: str(folder / v) if v else "" for k, v in outputs.items()}


def _build_datetime(df: pd.DataFrame) -> pd.Series:
    year = pd.to_numeric(df.get("year"), errors="coerce").fillna(2000).astype(int)
    month = pd.to_numeric(df.get("month"), errors="coerce").fillna(1).astype(int)
    day = pd.to_numeric(df.get("day"), errors="coerce").fillna(1).astype(int)
    hour_epw = pd.to_numeric(df.get("hour"), errors="coerce").fillna(1).astype(int)
    minute = pd.to_numeric(df.get("minute"), errors="coerce").fillna(0).astype(int)
    # EPW 1-24 -> normal saat 0-23
    hour_norm = (hour_epw - 1).clip(0, 23)
    return pd.to_datetime(dict(year=year, month=month, day=day, hour=hour_norm, minute=minute), errors="coerce")
